#ifndef WL_AUXPIN_H
#define WL_AUXPIN_H

#include <etl/enum_type.h>
#include <cstdint>

namespace wl {

struct AuxPin
{
    enum enum_type : uint32_t
    {
        HIGH_IMPEDANCE = 0,
        FIXED_HIGH_LOGIC_LEVEL = 1,
        FIXED_LOW_LOGIC_LEVEL = 2,
        INTERNAL_TRIGGER_OUTPUT = 3,
        EXTERNAL_TRIGGER_INPUT = 4,
        NUC_OFFSET_UPDATE_TRIGGER_OUTPUT = 5,
        NUC_OFFSET_UPDATE_REQUEST_INPUT = 6,
    };

    ETL_DECLARE_ENUM_TYPE(AuxPin, uint32_t)
    ETL_ENUM_TYPE(HIGH_IMPEDANCE, "HIGH_IMPEDANCE")
    ETL_ENUM_TYPE(FIXED_HIGH_LOGIC_LEVEL, "FIXED_HIGH_LOGIC_LEVEL")
    ETL_ENUM_TYPE(FIXED_LOW_LOGIC_LEVEL, "FIXED_LOW_LOGIC_LEVEL")
    ETL_ENUM_TYPE(INTERNAL_TRIGGER_OUTPUT, "INTERNAL_TRIGGER_OUTPUT")
    ETL_ENUM_TYPE(EXTERNAL_TRIGGER_INPUT, "EXTERNAL_TRIGGER_INPUT")
    ETL_ENUM_TYPE(NUC_OFFSET_UPDATE_TRIGGER_OUTPUT, "NUC_OFFSET_UPDATE_TRIGGER_OUTPUT")
    ETL_ENUM_TYPE(NUC_OFFSET_UPDATE_REQUEST_INPUT, "NUC_OFFSET_UPDATE_REQUEST_INPUT")
    ETL_END_ENUM_TYPE
};

} // namespace wl

#endif // WL_AUXPIN_H
